# Generated by Django 3.2 on 2021-05-19 19:16

from django.db import migrations, models
import linkapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(default=linkapp.models.generateCode, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('work_field', models.TextField(blank=True, default='')),
                ('user_count', models.IntegerField(default='0')),
            ],
        ),
    ]
